import express from 'express';
import userRoutes from './routes/user.routes';
import commerceRoutes from './routes/commerce.routes';
import productRoutes from './routes/product.routes';
import transactionRoutes from './routes/transaction.routes';
import qrcodeRoutes from './routes/qrcode.routes';
import cartRoutes from './routes/cart.routes';
import checkoutRoutes from './routes/checkout.routes';
import paymentRoutes from './routes/payment.routes';
const router = express.Router();

router.use('/users', userRoutes);
router.use('/commerces', commerceRoutes);
router.use('/products', productRoutes);
router.use('/cart', cartRoutes);
router.use('/transactions', transactionRoutes);
router.use('/qrcodes', qrcodeRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/payment', paymentRoutes);
export default router;
